language: ruby

sudo: required

dist: xenial

rvm:
  - 2.4
  - 2.5
  - 2.6
  - ruby-head

env:
  - browser=chrome
  - browser=firefox

gemfile:
  - Gemfile
  - gemfiles/Gemfile.low_spec
  - gemfiles/Gemfile.selenium-3.7

addons:
  chrome: stable
  firefox: latest

before_install:
  - gem install bundler

before_script:
  - |
    case $browser in
      firefox)
        wget https://github.com/mozilla/geckodriver/releases/download/v0.24.0/geckodriver-v0.24.0-linux64.tar.gz
        mkdir geckodriver
        tar -xzf geckodriver*.tar.gz -C .
        ;;
      chrome)
        sudo apt-get update -qq && sudo apt-get install -y chromium-chromedriver
        export PATH=$PATH:/usr/lib/chromium-browser/
        chromedriver -v
        ;;
    esac

services:
  - xvfb

script:
  - bundle exec rake

branches:
  only:
    - master
