language: ruby

sudo: required

dist: trusty

rvm:
  - 2.0.0
  - 2.1.10
  - 2.2.9
  - 2.3.6

env:
  - TARGET_BROWSER=chrome
  - TARGET_BROWSER=firefox

gemfile:
  - Gemfile

addons:
  chrome: stable

before_install:
  - gem install bundler

before_script:
  - |
    case $TARGET_BROWSER in
      firefox)
        wget https://github.com/mozilla/geckodriver/releases/download/v0.18.0/geckodriver-v0.18.0-linux64.tar.gz
        mkdir geckodriver
        tar -xzf geckodriver*.tar.gz -C geckodriver
        export PATH=$PATH:$PWD/geckodriver
        ;;
      chrome)
        sudo apt-get update -qq && sudo apt-get install -y chromium-chromedriver
        export PATH=$PATH:/usr/lib/chromium-browser/
        ;;
    esac
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - bundle exec rake

branches:
  only:
    - master
